
package view;

import controller.TaskController;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;


public class TaskDialogScreen extends javax.swing.JDialog {

    TaskController controller;
    Project project;
    
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        taskErrorField();
        
        controller = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToobar = new javax.swing.JPanel();
        jLabelToobarTarefaName = new javax.swing.JLabel();
        jLabelToobarTarefaSave = new javax.swing.JLabel();
        jPanelTarefas = new javax.swing.JPanel();
        jLabelTarefaName = new javax.swing.JLabel();
        jTextFieldTarefaName = new javax.swing.JTextField();
        jLabelDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescriptionTarefa = new javax.swing.JTextArea();
        jLabelPrazo = new javax.swing.JLabel();
        jFormattedTextFieldPrazoTarefa = new javax.swing.JFormattedTextField();
        jLabelNotasTarefa = new javax.swing.JLabel();
        jLabelNameError = new javax.swing.JLabel();
        jLabelDeadlineError = new javax.swing.JLabel();
        jTextAreaNotasTarefa = new javax.swing.JTextField();
        jLabelAdressError = new javax.swing.JLabel();
        jLabelWhatsappError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 600));
        setPreferredSize(new java.awt.Dimension(400, 600));

        jPanelToobar.setBackground(new java.awt.Color(255, 204, 0));

        jLabelToobarTarefaName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelToobarTarefaName.setForeground(new java.awt.Color(102, 51, 255));
        jLabelToobarTarefaName.setText("Pedido");

        jLabelToobarTarefaSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelToobarTarefaSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CheckRoxo.png"))); // NOI18N
        jLabelToobarTarefaSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelToobarTarefaSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelToobarTarefaSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelToobarLayout = new javax.swing.GroupLayout(jPanelToobar);
        jPanelToobar.setLayout(jPanelToobarLayout);
        jPanelToobarLayout.setHorizontalGroup(
            jPanelToobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToobarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelToobarTarefaName, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelToobarTarefaSave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelToobarLayout.setVerticalGroup(
            jPanelToobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelToobarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelToobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelToobarTarefaName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelToobarTarefaSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelTarefas.setBackground(java.awt.Color.white);

        jLabelTarefaName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTarefaName.setText("Produto");

        jTextFieldTarefaName.setMinimumSize(new java.awt.Dimension(6, 22));
        jTextFieldTarefaName.setPreferredSize(new java.awt.Dimension(6, 22));

        jLabelDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDescription.setText("Endereço");

        jTextAreaDescriptionTarefa.setColumns(20);
        jTextAreaDescriptionTarefa.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescriptionTarefa);

        jLabelPrazo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPrazo.setText("Data de entrega");

        jFormattedTextFieldPrazoTarefa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabelNotasTarefa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNotasTarefa.setText("What'sApp");

        jLabelNameError.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabelNameError.setForeground(new java.awt.Color(204, 0, 0));
        jLabelNameError.setText("Campo de Nome é obrigatório.");
        jLabelNameError.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelDeadlineError.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabelDeadlineError.setForeground(new java.awt.Color(204, 0, 51));
        jLabelDeadlineError.setText("Campo de Prazo é obrigatório.");

        jTextAreaNotasTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAreaNotasTarefaActionPerformed(evt);
            }
        });

        jLabelAdressError.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabelAdressError.setForeground(new java.awt.Color(204, 0, 51));
        jLabelAdressError.setText("Campo de Prazo é obrigatório.");

        jLabelWhatsappError.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabelWhatsappError.setForeground(new java.awt.Color(204, 0, 51));
        jLabelWhatsappError.setText("Campo de Prazo é obrigatório.");

        javax.swing.GroupLayout jPanelTarefasLayout = new javax.swing.GroupLayout(jPanelTarefas);
        jPanelTarefas.setLayout(jPanelTarefasLayout);
        jPanelTarefasLayout.setHorizontalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(jTextFieldTarefaName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTarefaName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPrazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldPrazoTarefa)
                    .addComponent(jLabelNotasTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDeadlineError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextAreaNotasTarefa)
                    .addComponent(jLabelAdressError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelWhatsappError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTarefasLayout.setVerticalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTarefaName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTarefaName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabelNameError)
                .addGap(18, 18, 18)
                .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabelAdressError)
                .addGap(18, 18, 18)
                .addComponent(jLabelPrazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldPrazoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabelDeadlineError)
                .addGap(20, 20, 20)
                .addComponent(jLabelNotasTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextAreaNotasTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWhatsappError)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelToobarTarefaSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelToobarTarefaSaveMouseClicked
        // TODO add your handling code here:
        
        try {
            if(!jTextFieldTarefaName.getText().equals("") && 
                    !jFormattedTextFieldPrazoTarefa.getText().equals("") &&
                    !jTextAreaDescriptionTarefa.getText().equals("") &&
                    !jTextAreaNotasTarefa.getText().equals("")){
                
                Task task = new Task();
                task.setIdFkTask(project.getIdProject());
                task.setProduct(jTextFieldTarefaName.getText());
                task.setAddress(jTextAreaDescriptionTarefa.getText());
                task.setContact(jTextAreaNotasTarefa.getText());
                task.setCompleted(false);
                // Formatando a data que está em texto para Date
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date deadline = null;
                try {
                    deadline = dateFormat.parse(jFormattedTextFieldPrazoTarefa.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(TaskDialogScreen.class.getName())
                            .log(Level.SEVERE, null, ex);
                }
                task.setDeadline(deadline);
                controller.save(task);
                JOptionPane.showMessageDialog(rootPane, "Tarefa SALVA com Sucesso.");
                this.dispose();
            }else{
                taskErrorField();
                
                if(jTextFieldTarefaName.getText().isEmpty()){
                    jLabelNameError.setVisible(true);
                }
                if(jFormattedTextFieldPrazoTarefa.getText().isEmpty()){
                    jLabelDeadlineError.setVisible(true);
                }
                if(jTextAreaDescriptionTarefa.getText().isEmpty()){
                    jLabelAdressError.setVisible(true);
                }
                if(jTextAreaNotasTarefa.getText().isEmpty()){
                    jLabelWhatsappError.setVisible(true);
                }
            }
        }catch (HeadlessException ex) {
             JOptionPane.showMessageDialog(rootPane, ex);
        }        
    }//GEN-LAST:event_jLabelToobarTarefaSaveMouseClicked

    private void jTextAreaNotasTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAreaNotasTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaNotasTarefaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldPrazoTarefa;
    private javax.swing.JLabel jLabelAdressError;
    private javax.swing.JLabel jLabelDeadlineError;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelNameError;
    private javax.swing.JLabel jLabelNotasTarefa;
    private javax.swing.JLabel jLabelPrazo;
    private javax.swing.JLabel jLabelTarefaName;
    private javax.swing.JLabel jLabelToobarTarefaName;
    private javax.swing.JLabel jLabelToobarTarefaSave;
    private javax.swing.JLabel jLabelWhatsappError;
    private javax.swing.JPanel jPanelTarefas;
    private javax.swing.JPanel jPanelToobar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescriptionTarefa;
    private javax.swing.JTextField jTextAreaNotasTarefa;
    private javax.swing.JTextField jTextFieldTarefaName;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project = project;
    }

    public void taskErrorField(){
        jLabelNameError.setVisible(false);
        jLabelAdressError.setVisible(false);
        jLabelDeadlineError.setVisible(false);
        jLabelWhatsappError.setVisible(false);
        
    }

}
